[tool.ruff]
target-version = "py312"
extend = "./styles/ruff.toml"
include = ["src/*"]
exclude = ["src/vendors/*", "guides/*"]

[tool.ruff.lint]
ignore = [
    "BLE001",  # Allow blind exception catch
    "T201",    # Allow prints
    "TRY002",  # Create own exception
    "TRY301",  # Allow raising exceptions
    "DOC201",  # Don't require returns in doc
    "DOC501",  # Don't require raises in doc
]
[tool.ruff.lint.per-file-ignores]
"src/brokerages/*" = [
    "PLR0913", # Allow too many arguments
    "PLR1702", # Allow many nested blocks
]
